/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negocio.Filme;
import Negocio.Sala2D;
import Negocio.Sala3D;
import Negocio.Sessao;
import Negocio.Cinema;
import Negocio.Ingresso;
import java.util.ArrayList;

/**
 *
 * @author Gleidson
 */
public class CineMaisPrincipal extends javax.swing.JFrame {
    private ArrayList<Filme> filme = new ArrayList<Filme>();
    private ArrayList<Sala2D> sala2d = new ArrayList<Sala2D>();
    private ArrayList<Sala3D> sala3d = new ArrayList<Sala3D>();
    private ArrayList<Sessao> sessao = new ArrayList<Sessao>();
    private ArrayList<Ingresso> ingresso = new ArrayList<Ingresso>();
    private ArrayList<Cinema> cinema = new ArrayList<Cinema>();

    /**
     * Creates new form CineMaisPrincipal
     */
    public CineMaisPrincipal() {        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCinema = new javax.swing.JPanel();
        botaoCadastroCinema = new javax.swing.JButton();
        PainelFilmes = new javax.swing.JPanel();
        botaoCadastrarFilme = new javax.swing.JButton();
        botaoAlterarFilme = new javax.swing.JButton();
        botaoExibirFilme = new javax.swing.JButton();
        PainelSalas = new javax.swing.JPanel();
        botaoExibirSala = new javax.swing.JButton();
        botaoAlterarSala3D = new javax.swing.JButton();
        botaoCadastrarSala3 = new javax.swing.JButton();
        botaoAlterarSala2D = new javax.swing.JButton();
        botaoCadastrarSala2 = new javax.swing.JButton();
        PainelSessoes = new javax.swing.JPanel();
        botaoCadastrarSessao2D = new javax.swing.JButton();
        botaoExibirSessao = new javax.swing.JButton();
        botaoCadastrarSessao3D = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoVenderIngresso = new javax.swing.JButton();
        botaoCancelarVenda = new javax.swing.JButton();
        ingressosVendidos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botaoConsultarVaga = new javax.swing.JButton();
        botaoConsultarCartaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelCinema.setBackground(new java.awt.Color(255, 255, 255));
        PainelCinema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Cinema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        botaoCadastroCinema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoCadastroCinema.setText("Cadastrar Cinema");
        botaoCadastroCinema.setPreferredSize(new java.awt.Dimension(159, 23));
        botaoCadastroCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroCinemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCinemaLayout = new javax.swing.GroupLayout(PainelCinema);
        PainelCinema.setLayout(PainelCinemaLayout);
        PainelCinemaLayout.setHorizontalGroup(
            PainelCinemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCinemaLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(botaoCadastroCinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCinemaLayout.setVerticalGroup(
            PainelCinemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCinemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCadastroCinema, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        PainelFilmes.setBackground(new java.awt.Color(255, 255, 255));
        PainelFilmes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        PainelFilmes.setPreferredSize(new java.awt.Dimension(190, 232));

        botaoCadastrarFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCadastrarFilme.setText("Cadastrar Filme");
        botaoCadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarFilmeActionPerformed(evt);
            }
        });

        botaoAlterarFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAlterarFilme.setText("Alterar Filme");
        botaoAlterarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarFilmeActionPerformed(evt);
            }
        });

        botaoExibirFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoExibirFilme.setText("Exibir Filmes");
        botaoExibirFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExibirFilmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFilmesLayout = new javax.swing.GroupLayout(PainelFilmes);
        PainelFilmes.setLayout(PainelFilmesLayout);
        PainelFilmesLayout.setHorizontalGroup(
            PainelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFilmesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botaoExibirFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(botaoAlterarFilme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarFilme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PainelFilmesLayout.setVerticalGroup(
            PainelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFilmesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(botaoCadastrarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoAlterarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoExibirFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        PainelSalas.setBackground(new java.awt.Color(255, 255, 255));
        PainelSalas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        PainelSalas.setPreferredSize(new java.awt.Dimension(190, 374));

        botaoExibirSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoExibirSala.setText("Exibir Salas");
        botaoExibirSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExibirSalaActionPerformed(evt);
            }
        });

        botaoAlterarSala3D.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAlterarSala3D.setText("Alterar Sala 3D");
        botaoAlterarSala3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarSala3DActionPerformed(evt);
            }
        });

        botaoCadastrarSala3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCadastrarSala3.setText("Cadastrar Sala 3D");
        botaoCadastrarSala3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarSala3ActionPerformed(evt);
            }
        });

        botaoAlterarSala2D.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoAlterarSala2D.setText("Alterar Sala 2D");
        botaoAlterarSala2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarSala2DActionPerformed(evt);
            }
        });

        botaoCadastrarSala2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCadastrarSala2.setText("Cadastrar Sala 2D");
        botaoCadastrarSala2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarSala2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelSalasLayout = new javax.swing.GroupLayout(PainelSalas);
        PainelSalas.setLayout(PainelSalasLayout);
        PainelSalasLayout.setHorizontalGroup(
            PainelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrarSala2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterarSala2D, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarSala3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterarSala3D, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExibirSala, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PainelSalasLayout.setVerticalGroup(
            PainelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSalasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(botaoCadastrarSala2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAlterarSala2D, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botaoCadastrarSala3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoAlterarSala3D, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(botaoExibirSala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        PainelSessoes.setBackground(new java.awt.Color(255, 255, 255));
        PainelSessoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sessoes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        PainelSessoes.setPreferredSize(new java.awt.Dimension(190, 230));

        botaoCadastrarSessao2D.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCadastrarSessao2D.setText("Cadastrar Sessão 2D");
        botaoCadastrarSessao2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarSessao2DActionPerformed(evt);
            }
        });

        botaoExibirSessao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoExibirSessao.setText("Exibir Sessões");
        botaoExibirSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExibirSessaoActionPerformed(evt);
            }
        });

        botaoCadastrarSessao3D.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoCadastrarSessao3D.setText("Cadastrar Sessão 3D");
        botaoCadastrarSessao3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarSessao3DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelSessoesLayout = new javax.swing.GroupLayout(PainelSessoes);
        PainelSessoes.setLayout(PainelSessoesLayout);
        PainelSessoesLayout.setHorizontalGroup(
            PainelSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSessoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelSessoesLayout.createSequentialGroup()
                        .addGroup(PainelSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoCadastrarSessao3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoCadastrarSessao2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelSessoesLayout.createSequentialGroup()
                        .addComponent(botaoExibirSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        PainelSessoesLayout.setVerticalGroup(
            PainelSessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSessoesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botaoCadastrarSessao2D, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarSessao3D, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoExibirSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bilheteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        botaoVenderIngresso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoVenderIngresso.setText("vender ingresso");
        botaoVenderIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderIngressoActionPerformed(evt);
            }
        });

        botaoCancelarVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoCancelarVenda.setText("cancelar venda");
        botaoCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarVendaActionPerformed(evt);
            }
        });

        ingressosVendidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingressosVendidos.setText("ingressos vendidos");
        ingressosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingressosVendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(botaoVenderIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(botaoCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ingressosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVenderIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingressosVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        botaoConsultarVaga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoConsultarVaga.setText("Consultar Vaga");
        botaoConsultarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarVagaActionPerformed(evt);
            }
        });

        botaoConsultarCartaz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoConsultarCartaz.setText("Filmes em Cartaz");
        botaoConsultarCartaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarCartazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(botaoConsultarVaga)
                .addGap(71, 71, 71)
                .addComponent(botaoConsultarCartaz)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConsultarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultarCartaz, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PainelSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PainelSessoes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PainelCinema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelCinema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PainelSessoes, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PainelSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PainelFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConsultarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarVagaActionPerformed
        TelaConsultarVaga tcv = new TelaConsultarVaga(sessao, filme);
        tcv.setVisible(true);
    }//GEN-LAST:event_botaoConsultarVagaActionPerformed

    private void botaoConsultarCartazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarCartazActionPerformed
        TelaFilmesEmCartaz tfc = new TelaFilmesEmCartaz(sessao, filme);
        tfc.setVisible(true);
    }//GEN-LAST:event_botaoConsultarCartazActionPerformed

    private void botaoVenderIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderIngressoActionPerformed
        TelaVenderIngresso tvi = new TelaVenderIngresso(sessao, ingresso, cinema);
        tvi.setVisible(true);
    }//GEN-LAST:event_botaoVenderIngressoActionPerformed

    private void botaoCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarVendaActionPerformed
        TelaCancelarVendaIngresso tcvi = new TelaCancelarVendaIngresso(ingresso, sessao);
        tcvi.setVisible(true);
    }//GEN-LAST:event_botaoCancelarVendaActionPerformed

    private void ingressosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingressosVendidosActionPerformed
        TelaExibirIngresso tei = new TelaExibirIngresso(ingresso);
        tei.setVisible(true);
    }//GEN-LAST:event_ingressosVendidosActionPerformed

    private void botaoCadastroCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroCinemaActionPerformed
        TelaCadastroCinema tcc = new TelaCadastroCinema(cinema);
        tcc.setVisible(true);
    }//GEN-LAST:event_botaoCadastroCinemaActionPerformed

    private void botaoCadastrarSessao3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarSessao3DActionPerformed
        TelaCadastroSessao3D tc3d = new TelaCadastroSessao3D(filme, sala3d, sessao);
        tc3d.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarSessao3DActionPerformed

    private void botaoExibirSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExibirSessaoActionPerformed
        TelaExibirSessao tes = new TelaExibirSessao(sessao, filme);
        tes.setVisible(true);
    }//GEN-LAST:event_botaoExibirSessaoActionPerformed

    private void botaoCadastrarSessao2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarSessao2DActionPerformed
        TelaCadastroSessao2D tcs = new TelaCadastroSessao2D(filme, sala2d, sessao);
        tcs.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarSessao2DActionPerformed

    private void botaoCadastrarSala2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarSala2ActionPerformed
        TelaCadastroSala2D t2d = new TelaCadastroSala2D(sala2d);
        t2d.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarSala2ActionPerformed

    private void botaoAlterarSala2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarSala2DActionPerformed
        TelaAlterarSala2D tas2d = new TelaAlterarSala2D(sala2d);
        tas2d.setVisible(true);
    }//GEN-LAST:event_botaoAlterarSala2DActionPerformed

    private void botaoCadastrarSala3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarSala3ActionPerformed
        TelaCadastroSala3D t3d = new TelaCadastroSala3D(sala3d);
        t3d.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarSala3ActionPerformed

    private void botaoAlterarSala3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarSala3DActionPerformed
        TelaAlterarSala3D tas3d = new TelaAlterarSala3D(sala3d);
        tas3d.setVisible(true);
    }//GEN-LAST:event_botaoAlterarSala3DActionPerformed

    private void botaoExibirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExibirSalaActionPerformed
        TelaExibirSala tes = new TelaExibirSala(sala2d, sala3d);
        tes.setVisible(true);
    }//GEN-LAST:event_botaoExibirSalaActionPerformed

    private void botaoExibirFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExibirFilmeActionPerformed
        // TODO add your handling code here:
        TelaExibirFilme tef = new TelaExibirFilme(filme);
        tef.setVisible(true);
    }//GEN-LAST:event_botaoExibirFilmeActionPerformed

    private void botaoAlterarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarFilmeActionPerformed
        TelaAlterarFilme taf = new TelaAlterarFilme(filme);
        taf.setVisible(true);
    }//GEN-LAST:event_botaoAlterarFilmeActionPerformed

    private void botaoCadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarFilmeActionPerformed
        // TODO add your handling code here:
        TelaCadastroFilme tcf = new TelaCadastroFilme(filme);
        tcf.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CineMaisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CineMaisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CineMaisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CineMaisPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CineMaisPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCinema;
    private javax.swing.JPanel PainelFilmes;
    private javax.swing.JPanel PainelSalas;
    private javax.swing.JPanel PainelSessoes;
    private javax.swing.JButton botaoAlterarFilme;
    private javax.swing.JButton botaoAlterarSala2D;
    private javax.swing.JButton botaoAlterarSala3D;
    private javax.swing.JButton botaoCadastrarFilme;
    private javax.swing.JButton botaoCadastrarSala2;
    private javax.swing.JButton botaoCadastrarSala3;
    private javax.swing.JButton botaoCadastrarSessao2D;
    private javax.swing.JButton botaoCadastrarSessao3D;
    private javax.swing.JButton botaoCadastroCinema;
    private javax.swing.JButton botaoCancelarVenda;
    private javax.swing.JButton botaoConsultarCartaz;
    private javax.swing.JButton botaoConsultarVaga;
    private javax.swing.JButton botaoExibirFilme;
    private javax.swing.JButton botaoExibirSala;
    private javax.swing.JButton botaoExibirSessao;
    private javax.swing.JButton botaoVenderIngresso;
    private javax.swing.JButton ingressosVendidos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
