/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negocio.Sala3D;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gleidson
 */
public class TelaCadastroSala3D extends javax.swing.JFrame {
    private ArrayList<Sala3D> sala3d = new ArrayList<Sala3D>();

    /**
     * Creates new form TelaSessao
     */
    public TelaCadastroSala3D(ArrayList<Sala3D> sala3d) {
        this.sala3d = sala3d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numeroSala = new javax.swing.JLabel();
        capacidadeSala = new javax.swing.JLabel();
        txtNumeroSala = new javax.swing.JTextField();
        txtCapacidadeSala = new javax.swing.JTextField();
        botaoSalvar2D = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        capacidadeSala1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Sala 3D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        numeroSala.setText("Sala:");

        capacidadeSala.setText("Capacidade:");

        botaoSalvar2D.setText("Salvar");
        botaoSalvar2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvar2DActionPerformed(evt);
            }
        });

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        capacidadeSala1.setText("Equipamentos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroSala)
                    .addComponent(capacidadeSala)
                    .addComponent(capacidadeSala1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSalvar2D)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(txtCapacidadeSala)
                        .addComponent(txtNumeroSala)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroSala)
                    .addComponent(txtNumeroSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidadeSala)
                    .addComponent(txtCapacidadeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadeSala1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(botaoSalvar2D)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvar2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvar2DActionPerformed
        // TODO add your handling code here:
        if (validarCampos()){
        Sala3D s3;
        int numero = Integer.parseInt(txtNumeroSala.getText());
        int capacidade = Integer.parseInt(txtCapacidadeSala.getText());
        String tipoSala = "3D";
        s3 = new Sala3D(numero, capacidade, tipoSala, txtDescricao.getText());
        
        sala3d.add(s3);
        
        JOptionPane.showMessageDialog(null, "Sala incluida com sucesso!");
        limpar();
        }
    }//GEN-LAST:event_botaoSalvar2DActionPerformed

    
    public void limpar(){
        txtNumeroSala.setText("");
        txtCapacidadeSala.setText("");
        txtDescricao.setText("");
    }
    
    public boolean validarCampos(){
        
        if (txtNumeroSala.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o numero da Sala");
            return false;
        }
        else if (txtCapacidadeSala.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a capacidade da Sala");
            return false;
        }
        else if (txtDescricao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe os equipamentos");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar2D;
    private javax.swing.JLabel capacidadeSala;
    private javax.swing.JLabel capacidadeSala1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeroSala;
    private javax.swing.JTextField txtCapacidadeSala;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNumeroSala;
    // End of variables declaration//GEN-END:variables
}
