/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import Negocio.Filme;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gleidson
 */
public class TelaAlterarFilme extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFilme
     */
    
    private ArrayList<Filme> filme = new ArrayList<Filme>();
    public TelaAlterarFilme(ArrayList<Filme> filme) {
        this.filme = filme;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelEditar = new javax.swing.JPanel();
        SelecaoFilmes = new javax.swing.JComboBox<>();
        tituloFilme = new javax.swing.JLabel();
        DiretorFilme = new javax.swing.JLabel();
        atorFilme = new javax.swing.JLabel();
        duracaoFilme = new javax.swing.JLabel();
        classificacaoFilme = new javax.swing.JLabel();
        categoriaFilme = new javax.swing.JLabel();
        textoFilme = new javax.swing.JTextField();
        textoDiretor = new javax.swing.JTextField();
        textoAtor = new javax.swing.JTextField();
        textoDuracao = new javax.swing.JTextField();
        textoClassificao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();
        painelDeletar = new javax.swing.JPanel();
        botaoExcluir = new javax.swing.JButton();
        painelEdicao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFilmes = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painelEditar.setBackground(new java.awt.Color(255, 255, 255));
        painelEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edição de Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        SelecaoFilmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Categoria", "Ação", "Comédia", "Infantil", "Suspense", "Terror" }));
        SelecaoFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoFilmesActionPerformed(evt);
            }
        });

        tituloFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloFilme.setText("Título do Filme:");

        DiretorFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DiretorFilme.setText("Diretor:");

        atorFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atorFilme.setText("Ator Principal:");

        duracaoFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        duracaoFilme.setText("Duração em minutos:");

        classificacaoFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classificacaoFilme.setText("Classificação Etária:");

        categoriaFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        categoriaFilme.setText("Categoria:");

        textoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFilmeActionPerformed(evt);
            }
        });

        textoAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAtorActionPerformed(evt);
            }
        });

        textoDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDuracaoActionPerformed(evt);
            }
        });

        textoClassificao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClassificaoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        botaoSalvar.setText("Salvar Alterações");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(botaoSalvar))
        );

        javax.swing.GroupLayout painelEditarLayout = new javax.swing.GroupLayout(painelEditar);
        painelEditar.setLayout(painelEditarLayout);
        painelEditarLayout.setHorizontalGroup(
            painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelEditarLayout.createSequentialGroup()
                        .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEditarLayout.createSequentialGroup()
                                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classificacaoFilme)
                                    .addComponent(categoriaFilme))
                                .addGap(32, 32, 32)
                                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SelecaoFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoClassificao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelEditarLayout.createSequentialGroup()
                                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duracaoFilme)
                                    .addComponent(atorFilme)
                                    .addComponent(DiretorFilme)
                                    .addComponent(tituloFilme))
                                .addGap(18, 18, 18)
                                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoAtor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEditarLayout.setVerticalGroup(
            painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiretorFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoDiretor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atorFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoAtor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duracaoFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoDuracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classificacaoFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoClassificao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelecaoFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaFilme))
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelDeletar.setBackground(new java.awt.Color(255, 255, 255));
        painelDeletar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deletar Filme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        botaoExcluir.setText("Excluir Item Seleciondado");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDeletarLayout = new javax.swing.GroupLayout(painelDeletar);
        painelDeletar.setLayout(painelDeletarLayout);
        painelDeletarLayout.setHorizontalGroup(
            painelDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeletarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoExcluir)
                .addGap(94, 94, 94))
        );
        painelDeletarLayout.setVerticalGroup(
            painelDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoExcluir)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        painelEdicao.setBackground(new java.awt.Color(255, 255, 255));
        painelEdicao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione o filme que deseja alterar ou excluir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tabelaFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Diretor", "Ator Principal", "Duração", "Classificação", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFilmes);

        javax.swing.GroupLayout painelEdicaoLayout = new javax.swing.GroupLayout(painelEdicao);
        painelEdicao.setLayout(painelEdicaoLayout);
        painelEdicaoLayout.setHorizontalGroup(
            painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelEdicaoLayout.setVerticalGroup(
            painelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelecaoFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoFilmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecaoFilmesActionPerformed

    private void textoAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAtorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAtorActionPerformed

    private void textoDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDuracaoActionPerformed

    private void textoClassificaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClassificaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClassificaoActionPerformed

    private void textoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFilmeActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        int i = tabelaFilmes.getSelectedRow();
        filme.remove(i);
        atualizarTabela();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
        
        if (validarCampos()){
        int i = tabelaFilmes.getSelectedRow();
        int min = Integer.parseInt(textoDuracao.getText());
        int indicacao = Integer.parseInt(textoClassificao.getText());
        
        filme.get(i).setTitulo(textoFilme.getText());
        filme.get(i).setDiretor(textoDiretor.getText());
        filme.get(i).setAtorPrincipal(textoAtor.getText());
        filme.get(i).setDuracaoMinutos(min);
        filme.get(i).setClassificacaoEtaria(indicacao);
        filme.get(i).setCategoria(SelecaoFilmes.getSelectedItem().toString());

        atualizarTabela();
        
        JOptionPane.showMessageDialog(null, "Filme alterado com sucesso!");
        limpar();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void tabelaFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesMouseClicked
        // TODO add your handling code here:
        int i = tabelaFilmes.getSelectedRow();
        
        textoFilme.setText(tabelaFilmes.getValueAt(i, 0).toString());
        textoDiretor.setText(tabelaFilmes.getValueAt(i, 1).toString());
        textoAtor.setText(tabelaFilmes.getValueAt(i, 2).toString());
        textoDuracao.setText(tabelaFilmes.getValueAt(i, 3).toString());
        textoClassificao.setText(tabelaFilmes.getValueAt(i, 4).toString());
        SelecaoFilmes.setSelectedItem(SelecaoFilmes.getSelectedItem().toString());
        
    }//GEN-LAST:event_tabelaFilmesMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel modelo = (DefaultTableModel) tabelaFilmes.getModel();
        modelo.setNumRows(0);
        
        for (Filme ft: filme){
            modelo.addRow(new Object []{
                ft.getTitulo(),
                ft.getDiretor(),
                ft.getAtorPrincipal(),
                ft.getDuracaoMinutos(),
                ft.getClassificacaoEtaria(),
                ft.getCategoria()
            });
        }
    }//GEN-LAST:event_formWindowOpened

    public void limpar(){
        textoFilme.setText("");
        textoDiretor.setText("");
        textoAtor.setText("");
        textoDuracao.setText("");
        textoClassificao.setText("");
        SelecaoFilmes.setSelectedIndex(0);
    }
    
    public boolean validarCampos(){
        
        if (textoFilme.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do filme");
            return false;
        }
        else if (textoDiretor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do Diretor");
            return false;
        }
        else if (textoAtor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do Ator Principal");
            return false;
        }
        else if (textoDuracao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a duração do filme em minutos");
            return false;
        }
        else if (textoClassificao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a classificação indicativa do filme");
            return false;
        }
        else if (SelecaoFilmes.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Selecione a Categoria do filme");
            return false;
        } 
        return true;
    }
    
    public void atualizarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaFilmes.getModel();
        modelo.setNumRows(0);
        
        for (Filme ft: filme){
            modelo.addRow(new Object []{
                ft.getTitulo(),
                ft.getDiretor(),
                ft.getAtorPrincipal(),
                ft.getDuracaoMinutos(),
                ft.getClassificacaoEtaria(),
                ft.getCategoria()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiretorFilme;
    private javax.swing.JComboBox<String> SelecaoFilmes;
    private javax.swing.JLabel atorFilme;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel categoriaFilme;
    private javax.swing.JLabel classificacaoFilme;
    private javax.swing.JLabel duracaoFilme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelDeletar;
    private javax.swing.JPanel painelEdicao;
    private javax.swing.JPanel painelEditar;
    private javax.swing.JTable tabelaFilmes;
    private javax.swing.JTextField textoAtor;
    private javax.swing.JTextField textoClassificao;
    private javax.swing.JTextField textoDiretor;
    private javax.swing.JTextField textoDuracao;
    private javax.swing.JTextField textoFilme;
    private javax.swing.JLabel tituloFilme;
    // End of variables declaration//GEN-END:variables
}
