/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;
import Negocio.Filme;
import java.util.ArrayList;

/**
 *
 * @author Gleidson
 */
public class TelaCadastroFilme extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFilme
     */
    
    private ArrayList<Filme> filme = new ArrayList<Filme>();
    public TelaCadastroFilme(ArrayList<Filme> filme){
        this.filme = filme;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SelecaoCategoria = new javax.swing.JComboBox<>();
        tituloFilme = new javax.swing.JLabel();
        DiretorFilme = new javax.swing.JLabel();
        atorFilme = new javax.swing.JLabel();
        duracaoFilme = new javax.swing.JLabel();
        classificacaoFilme = new javax.swing.JLabel();
        categoriaFilme = new javax.swing.JLabel();
        textoFilme = new javax.swing.JTextField();
        textoDiretor = new javax.swing.JTextField();
        textoAtor = new javax.swing.JTextField();
        textoDuracao = new javax.swing.JTextField();
        textoClassificao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        SelecaoCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Categoria", "Ação", "Comédia", "Infantil", "Suspense", "Terror" }));
        SelecaoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecaoCategoriaActionPerformed(evt);
            }
        });

        tituloFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloFilme.setText("Título do Filme:");

        DiretorFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DiretorFilme.setText("Diretor:");

        atorFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atorFilme.setText("Ator Principal:");

        duracaoFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        duracaoFilme.setText("Duração em minutos:");

        classificacaoFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classificacaoFilme.setText("Classificação Etária:");

        categoriaFilme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        categoriaFilme.setText("Categoria:");

        textoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFilmeActionPerformed(evt);
            }
        });

        textoAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAtorActionPerformed(evt);
            }
        });

        textoDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDuracaoActionPerformed(evt);
            }
        });

        textoClassificao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClassificaoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addGap(137, 137, 137))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoSalvar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classificacaoFilme)
                                    .addComponent(categoriaFilme))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SelecaoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoClassificao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duracaoFilme)
                                    .addComponent(atorFilme)
                                    .addComponent(DiretorFilme)
                                    .addComponent(tituloFilme))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoAtor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiretorFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoDiretor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atorFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoAtor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duracaoFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoDuracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classificacaoFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoClassificao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelecaoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaFilme))
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelecaoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecaoCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecaoCategoriaActionPerformed

    private void textoAtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAtorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAtorActionPerformed

    private void textoDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDuracaoActionPerformed

    private void textoClassificaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClassificaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClassificaoActionPerformed

    private void textoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFilmeActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
       
        if (validarCampos()){
        Filme f;
        int min = Integer.parseInt(textoDuracao.getText());
        int indicacao = Integer.parseInt(textoClassificao.getText());

        f = new Filme(textoFilme.getText(), textoDiretor.getText(), textoAtor.getText(), min, indicacao, SelecaoCategoria.getSelectedItem().toString());
        
        filme.add(f);
                
        JOptionPane.showMessageDialog(null, "Filme incluido com sucesso!");
        
        limpar();
    }
        
        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    public void limpar(){
        textoFilme.setText("");
        textoDiretor.setText("");
        textoAtor.setText("");
        textoDuracao.setText("");
        textoClassificao.setText("");
        SelecaoCategoria.setSelectedIndex(0);
    }
    
    public boolean validarCampos(){
        
        if (textoFilme.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do filme");
            return false;
        }
        else if (textoDiretor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do Diretor");
            return false;
        }
        else if (textoAtor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o nome do Ator Principal");
            return false;
        }
        else if (textoDuracao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a duração do filme em minutos");
            return false;
        }
        else if (textoClassificao.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a classificação indicativa do filme");
            return false;
        }
        else if (SelecaoCategoria.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Selecione a Categoria do filme");
            return false;
        } 
        return true;
    }    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiretorFilme;
    private javax.swing.JComboBox<String> SelecaoCategoria;
    private javax.swing.JLabel atorFilme;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel categoriaFilme;
    private javax.swing.JLabel classificacaoFilme;
    private javax.swing.JLabel duracaoFilme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textoAtor;
    private javax.swing.JTextField textoClassificao;
    private javax.swing.JTextField textoDiretor;
    private javax.swing.JTextField textoDuracao;
    private javax.swing.JTextField textoFilme;
    private javax.swing.JLabel tituloFilme;
    // End of variables declaration//GEN-END:variables
}
